# Generated by Django 4.1.1 on 2022-09-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_id_alter_answer_user_alter_comment_id_and_more'),
        ('main', '0003_initial'),
    ]

    operations = [
    ]
